### ISSUE TITLE
Function client_response.was_successful() return False instead of True

### ISSUE THREAD

**Issue by mao75** [FusionAuth/fusionauth-python-client#7]
Hi.
With this code:
client_response = client.exchange_o_auth_code_for_access_token(authCode,redirectURL,applicationID,clientSecret)
the value of client_response.was_successful() is True with version 1.18.0, but with 1.19.0 the returned value is False.
In the last case the error_response was: <Response [401]>

**Comment by mooreds** [comment]
Hiya,

I was able to login, however, the order of the arguments has changed to be more consistent with other libraries.

You can see some discussion about this issue here: https://fusionauth.io/community/forum/topic/311/trouble-getting-the-user-object-post-login/13

In particular, here's the order of parameters for that function: 

```
 resp = client.exchange_o_auth_code_for_access_token(request.args.get("code"), client_id, "http://localhost:5000/oauth-callback", client_secret)
```

You can see there that the `applicationID` is before the `redirectURL`. 

Can you please try that and see if it addresses the issue?

**Comment by mao75** [comment]
Hi! :)
Yes, the problem is (was...) the parameters order.

I wasted some time to understand that the problem was the version, but I
didn't think (nor had I found in the documentation) that the order of the
parameters had been changed.
:(
anyway it's ok!

thx

Il giorno ven 18 set 2020 alle ore 20:51 Dan Moore <notifications@github.com>
ha scritto:

**Comment by mooreds** [comment]
Yes, I agree we need to update the documentation. I have opened a PR for this: https://github.com/FusionAuth/fusionauth-site/pull/214

I'm glad you solved the issue. I'll close this out.
